
class Algorithms():

    def __init__(self):

        self.info = {
            "gp" : {
                "name" : "gp",
                "display_name" : "GP",
                "type" : "DEAP",
                "code" : "GP",
                "prefix" : "",
                "categories" : ["EA1a", "EA1b", "EA1c"],
                "ylim" : [[0.5, 0.61], [0.6, 0.9], [0.7, 0.9]],
                "file_index" : 1000,
            },
            "qdpy" : {
                "name" : "qdpy",
                "display_name" : "QDpy",
                "type" : "QDPY",
                "code" : "QD",
                "prefix" : "",
                "categories" : ["QD1a", "QD1b", "QD1c"],
                "ylim" : [[0.5, 0.6], [0.6, 0.9], [0.825, 0.88]],
                "file_index" : 1000,
            },
            "mt" : {
                "name" : "mtc",
                "display_name" : "Multi-Task",
                "type" : "MTC",
                "code" : "MTC_",
                "prefix" : "",
                "ylim" : [[0.5, 0.6], [0.6, 0.9], [0.825, 0.88]],
            },
            "mtc" : {
                "name" : "mtc",
                "display_name" : "Multi-Task Compatible",
                "type" : "MTC",
                "code" : "MTC",
                "prefix" : "",
                "ylim" : [[0.5, 0.6], [0.6, 0.9], [0.825, 0.88]],
                "file_index" : 1000,
            },
            "mti" : {
                "name" : "mti",
                "display_name" : "Multi-Task Incompatible",
                "type" : "MTI",
                "code" : "MTI",
                "prefix" : "",
                "ylim" : [[0.5, 0.6], [0.6, 0.9], [0.825, 0.88]],
                "file_index" : 1000,
            },
            "foraging_baseline" : {
                "name" : "foraging_baseline",
                "display_name" : "100cm",
                "type" : "Baseline",
                "code" : "Baseline",
                "prefix" : "",
                "ylim" : [[0.5, 0.6], [0.6, 0.9], [0.825, 0.88]],
                "generations" : 2200,
                "file_index" : 2200,
            },
            "foraging_qd1" : {
                "name" : "foraging_qd1",
                "display_name" : "QD Repertoire 1",
                "type" : "QD Repertoire 1",
                "code" : "QD1",
                "prefix" : "",
                "ylim" : [[0.5, 0.6], [0.6, 0.9], [0.825, 0.88]],
                "generations" : 1000,
                "file_index" : 1000,
            },
            "foraging_qd8" : {
                "name" : "foraging_qd8",
                "display_name" : "QD Repertoire 8",
                "type" : "QD Repertoire 8",
                "code" : "QD8",
                "prefix" : "",
                "ylim" : [[0.5, 0.6], [0.6, 0.9], [0.825, 0.88]],
                "generations" : 1000,
                "file_index" : 1000,
            },
            "foraging_qd64" : {
                "name" : "foraging_qd64",
                "display_name" : "QD Repertoire 64",
                "type" : "QD Repertoire 64",
                "code" : "QD64",
                "prefix" : "",
                "ylim" : [[0.5, 0.6], [0.6, 0.9], [0.825, 0.88]],
                "generations" : 1000,
                "file_index" : 1000,
            },
            "foraging_baseline_04" : {
                "name" : "foraging_baseline_04",
                "display_name" : "80cm",
                "type" : "Baseline",
                "code" : "Baseline",
                "prefix" : "",
                "generations" : 2200,
                "file_index" : 2200,
            },
            "foraging_qd1_04" : {
                "name" : "foraging_qd1_04",
                "display_name" : "QD Repertoire 1",
                "type" : "QD Repertoire 1",
                "code" : "QD1",
                "prefix" : "",
                "generations" : 1000,
                "file_index" : 1000,
            },
            "foraging_qd8_04" : {
                "name" : "foraging_qd8_04",
                "display_name" : "QD Repertoire 8",
                "type" : "QD Repertoire 8",
                "code" : "QD8",
                "prefix" : "",
                "generations" : 1000,
                "file_index" : 1000,
            },
            "foraging_qd64_04" : {
                "name" : "foraging_qd64_04",
                "display_name" : "QD Repertoire 64",
                "type" : "QD Repertoire 64",
                "code" : "QD64",
                "prefix" : "",
                "generations" : 1000,
                "file_index" : 1000,
            },
            "foraging_baseline_06" : {
                "name" : "foraging_baseline_06",
                "display_name" : "120cm",
                "type" : "Baseline",
                "code" : "Baseline",
                "prefix" : "",
                "generations" : 2200,
                "file_index" : 2200,
            },
            "foraging_qd1_06" : {
                "name" : "foraging_qd1_06",
                "display_name" : "QD Repertoire 1",
                "type" : "QD Repertoire 1",
                "code" : "QD1",
                "prefix" : "",
                "generations" : 1000,
                "file_index" : 1000,
            },
            "foraging_qd8_06" : {
                "name" : "foraging_qd8_06",
                "display_name" : "QD Repertoire 8",
                "type" : "QD Repertoire 8",
                "code" : "QD8",
                "prefix" : "",
                "generations" : 1000,
                "file_index" : 1000,
            },
            "foraging_qd64_06" : {
                "name" : "foraging_qd64_06",
                "display_name" : "QD Repertoire 64",
                "type" : "QD Repertoire 64",
                "code" : "QD64",
                "prefix" : "",
                "generations" : 1000,
                "file_index" : 1000,
            },
            "foraging_mt1" : {
                "name" : "foraging_mt1",
                "display_name" : "MT Repertoire 1",
                "type" : "MT Repertoire 1",
                "code" : "MT1",
                "prefix" : "",
                "generations" : 1000,
                "file_index" : 1000,
            },
            "foraging_mt8" : {
                "name" : "foraging_mt8",
                "display_name" : "MT Repertoire 8",
                "type" : "MT Repertoire 8",
                "code" : "MT8",
                "prefix" : "",
                "generations" : 1000,
                "file_index" : 1000,
            },
            "foraging_mt64" : {
                "name" : "foraging_mt64",
                "display_name" : "MT Repertoire 64",
                "type" : "MT Repertoire 64",
                "code" : "MT64",
                "prefix" : "",
                "generations" : 1000,
                "file_index" : 1000,
            },
        }
