
class Objectives():

    def __init__(self):

        self.index = ["density", "nest", "food", "idensity", "inest", "ifood", "foraging"]

        self.info = {
            "density" : {
                "name" : "density",
                "description" : "Increase neighbourhood density",
                "index" : 0,
                "identifier" : "d",
                "gp_url" : "../gp/results/density/",
                "qdpy_url": "../qdpy/results/density/",
                "mtc_url" : "../gp/results/density-nest-ifood/",
                "mti_url" : "../gp/results/density-nest-food/",
            },
            "nest" : {
                "name" : "nest",
                "description" : "Go to nest",
                "index" : 1,
                "identifier" : "n",
                "gp_url" : "../gp/results/nest/",
                "qdpy_url": "../qdpy/results/nest/",
                "mtc_url" : "../gp/results/density-nest-ifood/",
                "mti_url" : "../gp/results/density-nest-food/",
            },
            "food" : {
                "name" : "food",
                "description" : "Go to food",
                "index" : 2,
                "identifier" : "f",
                "gp_url" : "../gp/results/food/",
                "qdpy_url": "../qdpy/results/food/",
                "mtc_url" : "../gp/results/food-idensity-inest/",
                "mti_url" : "../gp/results/density-nest-food/",
            },
            "idensity" : {
                "name" : "idensity",
                "description" : "Reduce density",
                "index" : 3,
                "identifier" : "id",
                "gp_url" : "../gp/results/idensity/",
                "qdpy_url": "../qdpy/results/idensity/",
                "mtc_url": "../gp/results/food-idensity-inest/",
                "mti_url" : "../gp/results/idensity-inest-ifood/",
            },
            "inest" : {
                "name" : "inest",
                "description" : "Go away from nest",
                "index" : 4,
                "identifier" : "in",
                "gp_url" : "../gp/results/inest/",
                "qdpy_url": "../qdpy/results/inest/",
                "mtc_url": "../gp/results/food-idensity-inest/",
                "mti_url" : "../gp/results/idensity-inest-ifood/",
            },
            "ifood" : {
                "name" : "ifood",
                "description" : "Go away from food",
                "index" : 5,
                "identifier" : "if",
                "gp_url": "../gp/results/ifood/",
                "qdpy_url": "../qdpy/results/ifood/",
                "mtc_url": "../gp/results/density-nest-ifood/",
                "mti_url": "../gp/results/idensity-inest-ifood/",
            },
            "density-nest-food" : {
                "name" : "density-nest-food",
                "names" : ["density","nest","food"],
                "description" : ["Increase neighbourhood density", "Go to nest", "Go to food"],
                "mt_url": "../gp/test/density-nest-food/",
            },
            "foraging" : {
                "name" : "foraging",
                "description" : "Foraging",
                "index" : 6,
                "identifier" : "",
                "foraging_baseline_url":    "../gp/results/foraging/nest50/baseline/",
                "foraging_qd1_url":         "../gp/results/foraging/nest50/qd1/",
                "foraging_qd8_url":         "../gp/results/foraging/nest50/qd8/",
                "foraging_qd64_url":        "../gp/results/foraging/nest50/qd64/",
                "foraging_mt1_url":         "../gp/results/foraging/nest50/mt1/",
                "foraging_mt8_url":         "../gp/results/foraging/nest50/mt8/",
                "foraging_mt64_url":        "../gp/results/foraging/nest50/mt64/",
                "foraging_baseline_04_url": "../gp/results/nest40/baseline/",
                "foraging_qd1_04_url":      "../gp/results/nest40/qd1/",
                "foraging_qd8_04_url":      "../gp/results/nest40/qd8/",
                "foraging_qd64_04_url":     "../gp/results/nest40/qd64/",
                "foraging_baseline_06_url": "../gp/results/nest60/baseline/",
                "foraging_qd1_06_url":      "../gp/results/nest60/qd1/",
                "foraging_qd8_06_url":      "../gp/results/nest60/qd8/",
                "foraging_qd64_06_url":     "../gp/results/nest60/qd64/",
            },
        }
